version: '3.8'

services:
  configsvr:
    image: mongo:6.0
    container_name: configsvr
    command: mongod --configsvr --replSet configReplSet --port 27019
    ports:
      - "27019:27019"
    volumes:
      - configdb:/data/configdb

  shard1:
    image: mongo:6.0
    container_name: shard1
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018
    ports:
      - "27018:27018"
    volumes:
      - shard1db:/data/db

  shard2:
    image: mongo:6.0
    container_name: shard2
    command: mongod --shardsvr --replSet shard2ReplSet --port 27018
    ports:
      - "27020:27018"
    volumes:
      - shard2db:/data/db

  shard3:
    image: mongo:6.0
    container_name: shard3
    command: mongod --shardsvr --replSet shard3ReplSet --port 27018
    ports:
      - "27021:27018"
    volumes:
      - shard3db:/data/db

  mongos:
    image: mongo:6.0
    container_name: mongos
    command: mongos --configdb configReplSet/configsvr:27019 --port 27017
    ports:
      - "27017:27017"

volumes:
  configdb:
  shard1db:
  shard2db:
  shard3db:
